### ISSUE TITLE
✨ Add meta info to Story & Event pages

### ISSUE THREAD

**Issue by bartwr** [thehaguetech/thehaguetech-site#16]
Follow up of https://github.com/thehaguetech/thehaguetech-site/issues/15

**Comment by peter-jvt** [comment]
This seems to work but social media sites add a "/" to the route url:
https://www.thehaguetech.com/stories/tht-cribs-home-edition/

above link is therefore broken and returns the incorrect og meta tags

**Comment by dancomanlive** [comment]
The meta tags in _App.js are overriding the meta tags in story-details.js

The solution I found is to override the meta tags in _App.js(see code below). This works when typing in the complete url of a story but fails when going to a story via the navigation menu. The error when going to a story via the navigation menu is that the values from process.env are undefined.

`import Head from 'next/head';
import React from 'react';
import App, { Container } from 'next/app';
const contentful = require('contentful')

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};
    let story = null;

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);

      const client = await contentful.createClient({
        space: process.env.CONTENTFUL_SPACE_ID,
        accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
      })

      story = await client.getEntries({
        content_type: 'story',
        'fields.slug': pageProps.slug,
        limit: 1
      })
        .then((entry) => entry.items[0])
        .catch(console.error)
    }
    
    return { pageProps, story };
  }

  componentDidMount() {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register("/sw.js")
        .catch(err => console.error("Service worker registration failed", err));
    } else {
      console.log("Service worker not supported");
    }
  }

  render() {
    console.log('APP');
    const { Component, pageProps, story } = this.props;
    let storyImageUrl = null
    let storyTitle = null
    let storyDescription = null
    if (story) {
      const image = story.fields.smallImage.fields.file.url.slice(23);
      const url = "https://images.contentful.com/";
      storyImageUrl = url + image
      storyTitle = story.fields.title
      storyDescription = story.fields.longText.split("\n")[0]
    }
 
    return (
      <Container>
        <Head>
          <meta
            name="viewport"
            content="initial-scale=1.0, width=device-width"
            key="viewport"
          />

          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/static/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/static/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/static/favicon-16x16.png"
          />
          <link rel="manifest" href="/static/site.webmanifest" />
          <link
            rel="mask-icon"
            href="/static/safari-pinned-tab.svg"
            color="#0f2247"
          />
          <meta name="msapplication-TileColor" content="#ffffff" />
          <meta name="theme-color" content="#ffffff" />

          <meta
            key="og:title"
            property="og:title"
            content={storyTitle || "The Hague Tech"}
          />
          <meta
            key="og:image"
            property="og:image"
            content={storyImageUrl || "https://www.thehaguetech.com/static/pages/index/meta.jpg"}
          />
          <meta
            key="og:description"
            property="og:description"
            content={storyDescription ||
              "The largest tech community in The Hague, Netherlands offering office space, co-working space, event space, meeting space, co-creation labs, startup visa programme."
            }
          />
          <meta
            key="description"
            name="description"
            content={storyDescription ||
              "The largest tech community in The Hague, Netherlands offering office space, co-working space, event space, meeting space, co-creation labs, startup visa programme."
            }
          />

          <link
            href="/static/tht-favicon@2x.png"
            rel="icon"
            type="image/x-icon"
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(h,o,t,j,a,r){
              h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
              h._hjSettings={hjid:1360764,hjsv:6};
              a=o.getElementsByTagName('head')[0];
              r=o.createElement('script');r.async=1;
              r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
              a.appendChild(r);
          })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=')`,
            }}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `(function (i, s, o, g, r, a, m) {
              i['GoogleAnalyticsObject'] = r;
              i[r] = i[r] ||
                  function () {
                      (i[r].q = i[r].q || []).push(arguments)
                  }, i[r].l = 1 * new Date();
              a = s.createElement(o),
                  m = s.getElementsByTagName(o)[0];
              a.async = 1;
              a.src = g;
              m.parentNode.insertBefore(a, m)
          })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
          ga('create', 'UA-96526829-1', 'auto');
          ga('send', 'pageview');`,
            }}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `var appInsights=window.appInsights||function(a){
            function b(a){c[a]=function(){var b=arguments;c.queue.push(function(){c[a].apply(c,b)})}}var c={config:a},d=document,e=window;setTimeout(function(){var b=d.createElement("script");b.src=a.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js",d.getElementsByTagName("script")[0].parentNode.appendChild(b)});try{c.cookie=d.cookie}catch(a){}c.queue=[];for(var f=["Event","Exception","Metric","PageView","Trace","Dependency"];f.length;)b("track"+f.pop());if(b("setAuthenticatedUserContext"),b("clearAuthenticatedUserContext"),b("startTrackEvent"),b("stopTrackEvent"),b("startTrackPage"),b("stopTrackPage"),b("flush"),!a.disableExceptionTracking){f="onerror",b("_"+f);var g=e[f];e[f]=function(a,b,d,e,h){var i=g&&g(a,b,d,e,h);return!0!==i&&c["_"+f](a,b,d,e,h),i}}return c
          }({
            instrumentationKey: '2641f469-13f8-484f-a57f-39daebccd54c'
          });
          window.appInsights=appInsights,appInsights.queue&&0===appInsights.queue.length&&appInsights.trackPageView();`,
            }}
          />
        </Head>
        <style jsx global>{`
          * {
            box-sizing: border-box;
          }
          video,
          iframe {
            max-width: 100%;
          }
          html,
          body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            min-height: 100%;
          }
          html {
            overflow-x: hidden;
            overflow: auto;
          }
          body {
            font-size: 8px;
          }
          .root {
            overflow: hidden;
          }
          img {
            max-width: 100%;
          }
          p,
          li {
            font-family: "Maison Neue", sans-serif;
            max-width: 100%;
            font-size: 17px;
            line-height: 24px;
          }
          p > :global(a) {
            color: #1126a9;
            padding-bottom: 0;
            border-bottom: 1px solid rgba(15, 34, 72, 0.3);
            text-decoration: none;
          }
          p > :global(a:visited) {
            color: #0f2247;
          }
          .flex {
            display: flex;
            justify-content: space-between;
          }
          .flex-1 {
            flex: 1;
          }
          .flex-column {
            flex-direction: column;
          }
          .show-on-mobile-only {
            display: block;
          }
          @media (min-width: 480px) {
            .show-on-mobile-only {
              display: none;
            }
          }
          /* Noe Display */
          @font-face {
            font-family: "Noe Display";
            src: url("/static/fonts/noe-display/noe-display-regular.ttf")
              format("opentype");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "Noe Display";
            src: url("/static/fonts/noe-display/noe-display-bold.ttf")
              format("opentype");
            font-weight: bold;
            font-style: normal;
            font-display: fallback;
          }
          /* Maison Mono */
          @font-face {
            font-family: "maison_monobold";
            src: url("/static/fonts/maison-mono/maison_mono_bold-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-mono/maison_mono_bold-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_monoitalic";
            src: url("/static/fonts/maison-mono/maison_mono_italic-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-mono/maison_mono_italic-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_monolight";
            src: url("/static/fonts/maison-mono/maison_mono_light-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-mono/maison_mono_light-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_monoregular";
            src: url("/static/fonts/maison-mono/maison_mono_regular-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-mono/maison_mono_regular-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          /* Maison Neue */
          @font-face {
            font-family: "maison_neuebook_italic";
            src: url("/static/fonts/maison-neue/maisonneuebookitalic-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-neue/maisonneuebookitalic-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_neuebold_italic";
            src: url("/static/fonts/maison-neue/maisonneuebolditalic_1-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-neue/maisonneuebolditalic_1-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_neuebold";
            src: url("/static/fonts/maison-neue/maisonneuebold-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-neue/maisonneuebold-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "Maison Neue";
            src: url("/static/fonts/maison-neue/maisonneuebook-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-neue/maisonneuebook-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
          @font-face {
            font-family: "maison_neuebold_italic";
            src: url("/static/fonts/maison-neue/maisonneuebolditalic-webfont.woff2")
                format("woff2"),
              url("/static/fonts/maison-neue/maisonneuebolditalic-webfont.woff")
                format("woff");
            font-weight: normal;
            font-style: normal;
            font-display: fallback;
          }
        `}</style>
        <Component {...pageProps} />
      </Container>
    );
  }
}

export default MyApp;
`

**Comment by dancomanlive** [comment]
The solution to the problem above is to create a next.config.js with the following code:

```
module.exports = {
    env: {
        CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
        CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID
    },
  }
```

**Comment by bartwr** [comment]
@dancomanlive Your fix works great. 

Can be merged here: https://github.com/thehaguetech/thehaguetech-site/pull/21

The PR is deployed to production environment, https://www.thehaguetech.com/  Seems to work well.

____

Last part before closing this issue. Remove markdown tags from meta description.

![image](https://user-images.githubusercontent.com/899234/80155719-9a791e80-85c2-11ea-8323-8bc26d40a0ce.png)
